package org.example.view;

public enum Paginas {
    LOGIN,
    REGISTRAR,
    ENTRAR,
    MENU_PRINCIPAL,
    SAIR,
    PERFIL,
    LOCACOES_SOLICITADAS,
    LOCACOES_REGISTRO,
    ALUGAR_LIVRO,
    ADICIONAR_LIVRO,
    EDITAR_LIVRO,
    REMOVER_LIVRO,
    CADASTRAR_ADMIN,
    ENCERRAR
}
